# Welcome to Jekyll!
#

# Site settings
title: Yinpu Li
description: |
  The web page of Dr. Yinpu Li,
  Ph.D in the Department of
  Statistics, Florida State University
owner: Yinpu Li
first_published: 2022
email: yinpuli@icloud.com
baseurl: ""
# url: "http://localhost:4000"
permalink: pretty
collections:
  publications:
